
(PROGN
 (DEFMETHOD READ-DHCP-FROM-STREAM ((OBJ DHCP) INPUT-STREAM)
   (SETF (OP OBJ) (OCTETS->NUM (READ-OCTETS 1 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (HTYPE OBJ) (OCTETS->NUM (READ-OCTETS 1 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (HLEN OBJ) (OCTETS->NUM (READ-OCTETS 1 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (HOPS OBJ) (OCTETS->NUM (READ-OCTETS 1 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (XID OBJ) (OCTETS->NUM (READ-OCTETS 4 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (SECS OBJ) (OCTETS->NUM (READ-OCTETS 2 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (FLAGS OBJ) (OCTETS->NUM (READ-OCTETS 2 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (CIADDR OBJ) (OCTETS->NUM (READ-OCTETS 4 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (YIADDR OBJ) (OCTETS->NUM (READ-OCTETS 4 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (SIADDR OBJ) (OCTETS->NUM (READ-OCTETS 4 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (GIADDR OBJ) (OCTETS->NUM (READ-OCTETS 4 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (CHADDR OBJ) (OCTETS->NUM (READ-OCTETS 16 INPUT-STREAM) :ENDIAN :BIG))
   (SETF (SNAME OBJ)
           (LOOP :FOR I :UPTO 64
                 :COLLECT (READ-CHAR INPUT-STREAM)))
   (SETF (FILE OBJ)
           (LOOP :FOR I :UPTO 128
                 :COLLECT (READ-CHAR INPUT-STREAM)))
   (SETF (OPTIONS OBJ) (READ-SEQUENCE INPUT-STREAM))))