
(IN-PACKAGE :DHCP-SERVER)
(PROGN
 (DEFMETHOD READ-DHCP-FROM-STREAM ((OBJ DHCP) INPUT-STREAM)
   (SETF (OP OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 1 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (HTYPE OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 1 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (HLEN OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 1 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (HOPS OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 1 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (XID OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (SECS OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 2 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (FLAGS OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 2 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (CIADDR OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (YIADDR OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (SIADDR OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (GIADDR OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (CHADDR OBJ)
           (LOOP :FOR I :UPTO 16
                 :COLLECT (READ-BYTE INPUT-STREAM)))
   (SETF (SNAME OBJ)
           (LOOP :FOR I :UPTO 64
                 :COLLECT (READ-BYTE INPUT-STREAM)))
   (SETF (FILE OBJ)
           (LOOP :FOR I :UPTO 128
                 :COLLECT (READ-BYTE INPUT-STREAM)))
   (SETF (MCOOKIE OBJ)
           (NUMS-AND-TXT:OCTETS->NUM (NUMS-AND-TXT:READ-OCTETS 4 INPUT-STREAM)
                                     :ENDIAN :BIG))
   (SETF (OPTIONS OBJ)
           (LOOP :FOR X = (READ-BYTE INPUT-STREAM NIL NIL)
                 :WHILE X
                 :COLLECT X))))